In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
df = pd.read_csv("train.csv")
df.head()

traveller_ID  ticket_class  \
0          1214             3   
1           677             3   
2           534             2   
3          1174             3   
4           864             3   

                                                name     sex   age  \
0                                Smiljanic, Mr. Mile    male   NaN   
1                          Bostandyeff, Mr. Guentcho    male  26.0   
2  Phillips, Miss. Kate Florence ("Mrs Kate Louis...  female  19.0   
3                  Sage, Miss. Dorothy Edith "Dolly"  female   NaN   
4                     Henriksson, Miss. Jenny Lovisa  female  28.0   

   Siblings_spouses  Parchil   TickNum     fare cabin embarked MedBoat  \
0                 0        0    315037   8.6625   NaN        S     NaN   
1                 0        0    349224   7.8958   NaN        S     NaN   
2                 0        0    250655  26.0000   NaN        S      11   
3                 8        2  CA. 2343  69.5500   NaN        S     NaN   
4                 0        0    347086   7.7750   NaN        S     NaN   

   Survived  
0         0  
1         0  
2         1  
3         0  
4         0

In [2]:
df.shape

(916, 13)

In [3]:
df.count()

traveller_ID        916
ticket_class        916
name                916
sex                 916
age                 729
Siblings_spouses    916
Parchil             916
TickNum             916
fare                915
cabin               204
embarked            915
MedBoat             327
Survived            916
dtype: int64

In [4]:
df.columns

Index(['traveller_ID', 'ticket_class', 'name', 'sex', 'age',
       'Siblings_spouses', 'Parchil', 'TickNum', 'fare', 'cabin', 'embarked',
       'MedBoat', 'Survived'],
      dtype='object')

In [5]:
df.Survived.value_counts()

0    585
1    331
Name: Survived, dtype: int64

In [6]:
df.isnull().sum()

traveller_ID          0
ticket_class          0
name                  0
sex                   0
age                 187
Siblings_spouses      0
Parchil               0
TickNum               0
fare                  1
cabin               712
embarked              1
MedBoat             589
Survived              0
dtype: int64

In [7]:
df["embarked"] = df["embarked"].fillna("S")
df["fare"] = df["fare"].fillna(df["fare"].median())
df["age"] = df["age"].fillna(df["age"].median())
df["MedBoat"] = df["MedBoat"].fillna("11")
df["cabin"] = df["cabin"].fillna("B50")

In [8]:
df.isnull().sum()

traveller_ID        0
ticket_class        0
name                0
sex                 0
age                 0
Siblings_spouses    0
Parchil             0
TickNum             0
fare                0
cabin               0
embarked            0
MedBoat             0
Survived            0
dtype: int64

In [9]:
df.head()

traveller_ID  ticket_class  \
0          1214             3   
1           677             3   
2           534             2   
3          1174             3   
4           864             3   

                                                name     sex   age  \
0                                Smiljanic, Mr. Mile    male  28.0   
1                          Bostandyeff, Mr. Guentcho    male  26.0   
2  Phillips, Miss. Kate Florence ("Mrs Kate Louis...  female  19.0   
3                  Sage, Miss. Dorothy Edith "Dolly"  female  28.0   
4                     Henriksson, Miss. Jenny Lovisa  female  28.0   

   Siblings_spouses  Parchil   TickNum     fare cabin embarked MedBoat  \
0                 0        0    315037   8.6625   B50        S      11   
1                 0        0    349224   7.8958   B50        S      11   
2                 0        0    250655  26.0000   B50        S      11   
3                 8        2  CA. 2343  69.5500   B50        S      11   
4                 0        0    347086   7.7750   B50        S      11   

   Survived  
0         0  
1         0  
2         1  
3         0  
4         0

In [10]:
df.tail()

traveller_ID  ticket_class                             name     sex  \
911          1095             3   O'Sullivan, Miss. Bridget Mary  female   
912          1130             3  Pettersson, Miss. Ellen Natalia  female   
913          1294             3             Williams, Mr. Leslie    male   
914           860             3           Heikkinen, Miss. Laina  female   
915          1126             3          Petranec, Miss. Matilda  female   

      age  Siblings_spouses  Parchil           TickNum     fare cabin  \
911  28.0                 0        0            330909   7.6292   B50   
912  18.0                 0        0            347087   7.7750   B50   
913  28.5                 0        0             54636  16.1000   B50   
914  26.0                 0        0  STON/O2. 3101282   7.9250   B50   
915  28.0                 0        0            349245   7.8958   B50   

    embarked MedBoat  Survived  
911        Q      11         0  
912        S      11         0  
913        S      11         0  
914        S      11         1  
915        S      11         0

In [11]:
df.loc[df["sex"]=="male", "sex"] = 0
df.loc[df["sex"]=="female", "sex"] = 1

In [12]:
df.embarked.value_counts()

S    639
C    187
Q     90
Name: embarked, dtype: int64

In [13]:
df.columns

Index(['traveller_ID', 'ticket_class', 'name', 'sex', 'age',
       'Siblings_spouses', 'Parchil', 'TickNum', 'fare', 'cabin', 'embarked',
       'MedBoat', 'Survived'],
      dtype='object')

In [14]:
df.dtypes

traveller_ID          int64
ticket_class          int64
name                 object
sex                   int64
age                 float64
Siblings_spouses      int64
Parchil               int64
TickNum              object
fare                float64
cabin                object
embarked             object
MedBoat              object
Survived              int64
dtype: object

In [15]:
dt = df.drop(["name", "cabin", "TickNum", "MedBoat"], axis=1)
dt.head()

traveller_ID  ticket_class  sex   age  Siblings_spouses  Parchil     fare  \
0          1214             3    0  28.0                 0        0   8.6625   
1           677             3    0  26.0                 0        0   7.8958   
2           534             2    1  19.0                 0        0  26.0000   
3          1174             3    1  28.0                 8        2  69.5500   
4           864             3    1  28.0                 0        0   7.7750   

  embarked  Survived  
0        S         0  
1        S         0  
2        S         1  
3        S         0  
4        S         0

In [16]:
from sklearn.preprocessing import LabelEncoder
labE = LabelEncoder()
X=dt
X["embarked"] = labE.fit_transform(X["embarked"])
X

traveller_ID  ticket_class  sex      age  Siblings_spouses  Parchil  \
0            1214             3    0  28.0000                 0        0   
1             677             3    0  26.0000                 0        0   
2             534             2    1  19.0000                 0        0   
3            1174             3    1  28.0000                 8        2   
4             864             3    1  28.0000                 0        0   
5             895             3    1   1.0000                 1        1   
6             813             3    0  28.0000                 0        0   
7             745             3    1  30.0000                 0        0   
8            1030             3    0  28.0000                 0        0   
9            1072             3    0  28.0000                 0        0   
10            425             2    0  52.0000                 0        0   
11            846             3    0  20.0000                 0        0   
12           1245             3    0  28.0000                 0        0   
13            321             1    0  62.0000                 0        0   
14            847             3    0  23.5000                 0        0   
15            989             3    0  28.0000                 0        0   
16            654             3    0  20.0000                 0        0   
17           1003             3    0  28.0000                 2        0   
18            433             2    0  30.0000                 0        0   
19             39             1    0  48.0000                 0        0   
20             30             1    0  45.0000                 0        0   
21            242             1    1  33.0000                 0        0   
22            796             3    0  40.5000                 0        0   
23            906             3    0  27.0000                 0        0   
24            136             1    0  53.0000                 0        0   
25            310             1    0  57.0000                 1        1   
26           1092             3    0  20.0000                 0        0   
27            852             3    1  28.0000                 0        0   
28            442             2    0  24.0000                 2        0   
29           1156             3    1   2.0000                 1        1   
..            ...           ...  ...      ...               ...      ...   
886           510             2    0  16.0000                 0        0   
887          1082             3    0   9.0000                 0        1   
888           474             2    0  31.0000                 0        0   
889           856             3    1  28.0000                 0        0   
890           747             3    0   0.3333                 0        2   
891           252             1    0  61.0000                 1        3   
892            21             1    1  47.0000                 1        1   
893           459             2    0  42.0000                 1        0   
894          1184             3    0  28.0000                 2        0   
895           276             1    0  57.0000                 1        0   
896           955             3    1  28.0000                 3        1   
897          1215             3    0  28.0000                 0        0   
898           385             2    0   8.0000                 1        1   
899           805             3    0  28.0000                 0        0   
900           343             2    0  34.0000                 0        0   
901           769             3    0  22.0000                 0        0   
902           130             1    1  22.0000                 0        1   
903           871             3    0  28.0000                 0        0   
904          1123             3    1  28.0000                 0        2   
905            87             1    0  27.0000                 0        0   
906           330             2    0  57.0000        

In [17]:
from sklearn.preprocessing import OneHotEncoder
OneH = OneHotEncoder(categorical_features=[-3])
X = OneH.fit_transform(X).toarray()
X

array([[0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 0., ..., 0., 2., 1.],
       ...,
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 0., ..., 0., 2., 1.],
       [0., 0., 0., ..., 0., 2., 0.]])

In [18]:
X = X[:, 1:]
X

array([[0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 0., ..., 0., 2., 1.],
       ...,
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 0., ..., 0., 2., 1.],
       [0., 0., 0., ..., 0., 2., 0.]])

In [19]:
X = dt[["traveller_ID", "ticket_class", "sex", "age", "Siblings_spouses", "Parchil", "fare", "embarked"]].values
X

array([[1.2140e+03, 3.0000e+00, 0.0000e+00, ..., 0.0000e+00, 8.6625e+00,
        2.0000e+00],
       [6.7700e+02, 3.0000e+00, 0.0000e+00, ..., 0.0000e+00, 7.8958e+00,
        2.0000e+00],
       [5.3400e+02, 2.0000e+00, 1.0000e+00, ..., 0.0000e+00, 2.6000e+01,
        2.0000e+00],
       ...,
       [1.2940e+03, 3.0000e+00, 0.0000e+00, ..., 0.0000e+00, 1.6100e+01,
        2.0000e+00],
       [8.6000e+02, 3.0000e+00, 1.0000e+00, ..., 0.0000e+00, 7.9250e+00,
        2.0000e+00],
       [1.1260e+03, 3.0000e+00, 1.0000e+00, ..., 0.0000e+00, 7.8958e+00,
        2.0000e+00]])

In [20]:
y = dt.Survived
y.head()

0    0
1    0
2    1
3    0
4    0
Name: Survived, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30,random_state =42)

In [22]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)

In [23]:
from sklearn.linear_model import LogisticRegression
ln = LogisticRegression()
model = ln.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0], dtype=int64)

In [24]:
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))

[[159  23]
 [ 25  68]]


In [25]:
print(classification_report(y_test,y_pred))

             precision    recall  f1-score   support

          0       0.86      0.87      0.87       182
          1       0.75      0.73      0.74        93

avg / total       0.82      0.83      0.82       275



In [26]:
print (accuracy_score(y_test, model.predict(X_test)))

0.8254545454545454


In [27]:
test = pd.read_csv('test.csv')
test.head()

traveller_ID  ticket_class                      name   sex   age  \
0          1148           3.0      Rintamaki, Mr. Matti  male  35.0   
1          1049           3.0          Nakid, Mr. Sahid  male  20.0   
2           982           3.0     Lyntakoff, Mr. Stanko  male   NaN   
3           808           3.0          Ford, Mr. Arthur  male   NaN   
4          1195           3.0  Shaughnessy, Mr. Patrick  male   NaN   

   Siblings_spouses  Parchil            TickNum     fare cabin embarked  \
0               0.0      0.0  STON/O 2. 3101273   7.1250   NaN        S   
1               1.0      1.0               2653  15.7417   NaN        C   
2               0.0      0.0             349235   7.8958   NaN        S   
3               0.0      0.0           A/5 1478   8.0500   NaN        S   
4               0.0      0.0             370374   7.7500   NaN        Q   

  MedBoat  
0     NaN  
1       C  
2     NaN  
3     NaN  
4     NaN

In [28]:
data = test.drop(["cabin", "name", "TickNum", "traveller_ID", "MedBoat", "fare"], axis =1)
data.head()

ticket_class   sex   age  Siblings_spouses  Parchil embarked
0           3.0  male  35.0               0.0      0.0        S
1           3.0  male  20.0               1.0      1.0        C
2           3.0  male   NaN               0.0      0.0        S
3           3.0  male   NaN               0.0      0.0        S
4           3.0  male   NaN               0.0      0.0        Q

In [29]:
data.isnull().sum()

ticket_class         0
sex                  0
age                 76
Siblings_spouses     0
Parchil              0
embarked             1
dtype: int64

In [30]:
data.loc[data["sex"]=="male", "sex"] = 0
data.loc[data["sex"]=="female", "sex"] = 1

In [31]:
data.head()

ticket_class  sex   age  Siblings_spouses  Parchil embarked
0           3.0    0  35.0               0.0      0.0        S
1           3.0    0  20.0               1.0      1.0        C
2           3.0    0   NaN               0.0      0.0        S
3           3.0    0   NaN               0.0      0.0        S
4           3.0    0   NaN               0.0      0.0        Q

In [32]:
data["embarked"] = data["embarked"].fillna("S")

In [33]:
data["age"] = data["age"].fillna(data["age"].median())

In [34]:
data.isnull().sum()

ticket_class        0
sex                 0
age                 0
Siblings_spouses    0
Parchil             0
embarked            0
dtype: int64

In [35]:
data.head()

ticket_class  sex   age  Siblings_spouses  Parchil embarked
0           3.0    0  35.0               0.0      0.0        S
1           3.0    0  20.0               1.0      1.0        C
2           3.0    0  30.0               0.0      0.0        S
3           3.0    0  30.0               0.0      0.0        S
4           3.0    0  30.0               0.0      0.0        Q

In [36]:
td = pd.get_dummies(data)
td.head()

ticket_class  sex   age  Siblings_spouses  Parchil  embarked_C  embarked_Q  \
0           3.0    0  35.0               0.0      0.0           0           0   
1           3.0    0  20.0               1.0      1.0           1           0   
2           3.0    0  30.0               0.0      0.0           0           0   
3           3.0    0  30.0               0.0      0.0           0           0   
4           3.0    0  30.0               0.0      0.0           0           1   

   embarked_S  
0           1  
1           0  
2           1  
3           1  
4           0

In [37]:
td.shape

(393, 8)

In [38]:
X.shape

(916, 8)

In [39]:
y_pred = model.predict(td)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [40]:
y_pred.shape

(393,)

In [41]:
test.shape

(393, 12)

In [42]:
test.head()

traveller_ID  ticket_class                      name   sex   age  \
0          1148           3.0      Rintamaki, Mr. Matti  male  35.0   
1          1049           3.0          Nakid, Mr. Sahid  male  20.0   
2           982           3.0     Lyntakoff, Mr. Stanko  male   NaN   
3           808           3.0          Ford, Mr. Arthur  male   NaN   
4          1195           3.0  Shaughnessy, Mr. Patrick  male   NaN   

   Siblings_spouses  Parchil            TickNum     fare cabin embarked  \
0               0.0      0.0  STON/O 2. 3101273   7.1250   NaN        S   
1               1.0      1.0               2653  15.7417   NaN        C   
2               0.0      0.0             349235   7.8958   NaN        S   
3               0.0      0.0           A/5 1478   8.0500   NaN        S   
4               0.0      0.0             370374   7.7500   NaN        Q   

  MedBoat  
0     NaN  
1       C  
2     NaN  
3     NaN  
4     NaN

In [43]:
vit = test
vit.head()

traveller_ID  ticket_class                      name   sex   age  \
0          1148           3.0      Rintamaki, Mr. Matti  male  35.0   
1          1049           3.0          Nakid, Mr. Sahid  male  20.0   
2           982           3.0     Lyntakoff, Mr. Stanko  male   NaN   
3           808           3.0          Ford, Mr. Arthur  male   NaN   
4          1195           3.0  Shaughnessy, Mr. Patrick  male   NaN   

   Siblings_spouses  Parchil            TickNum     fare cabin embarked  \
0               0.0      0.0  STON/O 2. 3101273   7.1250   NaN        S   
1               1.0      1.0               2653  15.7417   NaN        C   
2               0.0      0.0             349235   7.8958   NaN        S   
3               0.0      0.0           A/5 1478   8.0500   NaN        S   
4               0.0      0.0             370374   7.7500   NaN        Q   

  MedBoat  
0     NaN  
1       C  
2     NaN  
3     NaN  
4     NaN

In [44]:
vit["Survived"] = y_pred
vit.head()

traveller_ID  ticket_class                      name   sex   age  \
0          1148           3.0      Rintamaki, Mr. Matti  male  35.0   
1          1049           3.0          Nakid, Mr. Sahid  male  20.0   
2           982           3.0     Lyntakoff, Mr. Stanko  male   NaN   
3           808           3.0          Ford, Mr. Arthur  male   NaN   
4          1195           3.0  Shaughnessy, Mr. Patrick  male   NaN   

   Siblings_spouses  Parchil            TickNum     fare cabin embarked  \
0               0.0      0.0  STON/O 2. 3101273   7.1250   NaN        S   
1               1.0      1.0               2653  15.7417   NaN        C   
2               0.0      0.0             349235   7.8958   NaN        S   
3               0.0      0.0           A/5 1478   8.0500   NaN        S   
4               0.0      0.0             370374   7.7500   NaN        Q   

  MedBoat  Survived  
0     NaN         1  
1       C         1  
2     NaN         1  
3     NaN         1  
4     NaN         1

In [45]:
vit.columns

Index(['traveller_ID', 'ticket_class', 'name', 'sex', 'age',
       'Siblings_spouses', 'Parchil', 'TickNum', 'fare', 'cabin', 'embarked',
       'MedBoat', 'Survived'],
      dtype='object')

In [46]:
final = vit.drop(['ticket_class', 'name', 'sex', 'age', 'Siblings_spouses', 'Parchil',
       'TickNum', 'fare', 'cabin', 'embarked', 'MedBoat' ], axis =1)
final.head()

traveller_ID  Survived
0          1148         1
1          1049         1
2           982         1
3           808         1
4          1195         1

In [47]:
answers = final.to_csv("Abuja_OnuigweVitus.csv")
final.columns

Index(['traveller_ID', 'Survived'], dtype='object')